export const selectInputText = 'Select Suburb'

export const suburbList: string[] = [
  'Alexandria',
  'Annandale',
  'Ashfield',
  'Balmain',
  'Bankstown',
  'Bellevue Hill',
  'Castle Hill',
  'Campbelltown',
  'Canterbury',
  'Chatswood',
  'Chippendale',
  'Croydon',
  'Darling Point',
  'Double Bay',
  'Eastwood',
  'Epping',
  'Flemington',
  'Granville',
  'Hornsby',
  'Kellyville',
  'Lidcombe',
  'Liverpool',
  'Macquarie Park',
  'Neutral Bay',
  'North Parramatta',
  'North Kellyville',
  'Norwest',
  'Parramatta',
  'Penrith',
  'Pyrmont',
  'Rose Hill',
  'Rouse Hill',
  'Seven Hills',
  'Silverwater',
  'Strathfield',
  'Sydney Olympic Park',
  'Waterloo',
  'West Ryde',
  'Wentworthville'
]
